### ISSUE TITLE
flexbex_core failing with routing congestion too high

### ISSUE THREAD

**Issue by vijayank88** [phthinh/soric_project#2]
Hi,
I'm trying run your setup locally, but its throwing routing congestion too high always.

`set ::env(SYNTH_STRATEGY) "DELAY 2"` If I remove this lines everything works fine. 
https://github.com/phthinh/soric_project/blob/a15b32788eab5c1f386d8eb8a76979bba4fdb973/openlane/flexbex_core/config.tcl#L34

Do you have any suggestion to proceed further?

Thanks in advance...

**Comment by phthinh** [comment]
Hi @vijayank88,
I didn't face this issue. I think it is probably due to the difference in the version of the tools we used. 
`set ::env(SYNTH_STRATEGY)` configs the strategies for `abc` logic synthesis and technology mapping. 
I am not 100% sure if somehow it affects the routing process. I set this config because I want to prioritize the timing over the area. By default, the config is AREA 0.
Anyway, if your config set is working so that GDS file can be generated, that should be fine :).
